spring:
  datasource:
    url: jdbc:h2:mem:challenge_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

server:
  port: 9090

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html